/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package consulting.hippone

import arrow.continuations.SuspendApp
import arrow.continuations.ktor.server
import arrow.fx.coroutines.resourceScope
import io.ktor.server.netty.*
import kotlinx.coroutines.awaitCancellation

fun main(): Unit = SuspendApp{
    resourceScope {
        server(Netty, port = 8080, host = "localhost") {
            examinr()
        }
        awaitCancellation()
    }
}
